#! /usr/bin/perl -w
#
#usage: <prog> <*.dis>
#
#function: print out each unique full instruction and its occurrence
#

eval '$'.$1.'$2;' while $ARGV[0] =~ /^([A-Za-z_]+=)(.*)/ && shift;

while(<>) {
    next	if(! s/^\s*(\w+):\s+//);	#remove ' addr:	'
    $pc= hex($1);
    ++ $total;
    chop;
    s///g;
    if(s/ <.*>//) {				#remove trailing <symbol>
	s/(\w+)$//;
	$targ= $1;
	$offset= hex($targ) - $pc;
	/.*\t(.+)$/;
	++ $icount{$1.$targ};
	$inst= 'offset-' . $1 . sprintf("%d", $offset);
    }elsif(/.*\t(.+)/) {
	++ $icount{$1};
    }
}
$ratio= 100.0/$total;

foreach $i (sort {$icount{$b}<=>$icount{$a}} keys %icount) {
    $c= $icount{$i};
    $acc+= $c;
    printf("%30s = %6d = %5.2f%% %5.2f%%\n", $i, $c, $c*$ratio, $acc*$ratio);
}
