
/**
 **************************************************************************************
 * @file    user_defined_effect_api.h
 * @brief   interface for user defined effect algorithm
 *          Automatically generated by the script, no manual modification required.
 *
 * @author  Castle Cai
 * @version V1.0.0
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 **************************************************************************************
 */

#include "roboeffect_api.h"
#include "roboeffect_config.h"



#include "simple_gain.h" 


#ifndef SIMPLE_GAIN_ENABLE
#define SIMPLE_GAIN_ENABLE                 (1)
#endif


//Add SIMPLE_GAIN_INFO_DATA to USER_DEFINED_LIBS_DATA
#define SIMPLE_GAIN_INFO_DATA \
0x58, 0x00, \
0x01, 0x00, 0x00, /*version*/\
0x0B, /*name length*/\
0x73, 0x69, 0x6D, 0x70, 0x6C, 0x65, 0x5F, 0x67, 0x61, 0x69, 0x6E, /*simple_gain*/\
0x00, /*not node*/\
0x02, /*bitwidth:16/24*/\
0x06, /*frame size formula length*/\
0x46, 0x5A, 0x5F, 0x41, 0x4E, 0x59, /*FZ_ANY*/\
0x01, /*input counter:1*/\
0x00, /*no input discript*/\
0x03, /*in1 ch:mono/stereo*/\
0x03, /*output channel*/\
/*parameter start--->*/\
0x03, /*effect param number:3*/\
/*param name: mute*/\
0x04, /*name size:4*/\
0x6D, 0x75, 0x74, 0x65, /*mute*/\
0x00, /*param type:bool*/\
0x00, 0x00, \
0x00, 0x00, \
/*param name: gain*/\
0x04, /*name size:4*/\
0x67, 0x61, 0x69, 0x6E, /*gain*/\
0x02, /*param type:value*/\
/*value:-9000,1200,10*/ \
0xD8, 0xDC, \
0xB0, 0x04, \
0x0A, 0x00, \
0x00, 0x00, \
0x00, 0x00, \
/*param name: filter0*/\
0x07, /*name size:7*/\
0x66, 0x69, 0x6C, 0x74, 0x65, 0x72, 0x30, /*filter0*/\
0x05, /*param type:vector*/\
0x08, /*vector:float*/\
0x00, 0x00, \
0x01, 0x00, \
/*ui display--->*/\
0x00, /*type:bool,check_box*/\
/*ui display--->*/\
0x01, /*type:value,hslider*/\
0x02, /*unit content size:2*/\
0x64, 0x42, \
0x02, /*fract*/\
0x64, 0x00, /*ratio*/\
0x00, /*no tips*/\
/*ui display--->*/\
0x00, /*type:vector,push_button*/\
0x01, /*ui layout:manual*/\
/*ui layout*/\
0x02, 0x0C, /*row size, column size*/\
0x01, 0x03, /*grid row, grid column*/\
0x01, 0xFF, /*grid row, grid column*/\
0x02, 0x01, /*grid row, grid column*/


//simple_gain interface
bool roboeffect_simple_gain_init_if(void *node);
bool roboeffect_simple_gain_config_if(void *node, int16_t *new_param, uint8_t param_num, uint8_t len);
bool roboeffect_simple_gain_apply_if(void *node, int16_t *pcm_in1, int16_t *pcm_in2, int16_t *pcm_out, int32_t n);
int32_t roboeffect_simple_gain_memory_size_if(roboeffect_memory_size_query *query, roboeffect_memory_size_response *response);


//Add SIMPLE_GAIN_INTERFACE to USER_DEFINED_INTERFACE
#if SIMPLE_GAIN_ENABLE
#define SIMPLE_GAIN_INTERFACE \
	{ROBOEFFECT_SIMPLE_GAIN, ROBOEFFECT_CH_MONO_STEREO, 3, FZ_ANY, 0, {0},\
	roboeffect_simple_gain_init_if, roboeffect_simple_gain_config_if, roboeffect_simple_gain_apply_if, roboeffect_simple_gain_memory_size_if,\
	},
#else
#define SIMPLE_GAIN_INTERFACE \
	{ROBOEFFECT_SIMPLE_GAIN, ROBOEFFECT_CH_MONO_STEREO, 3, FZ_ANY, 0, {0},\
	roboeffect_null_init_if, roboeffect_null_config_if, roboeffect_null_apply_if, roboeffect_null_memory_size_if,\
	},
#endif


#define USER_DEFINED_INTERFACE \
	SIMPLE_GAIN_INTERFACE

#define USER_DEFINED_LIBS_DATA \
	SIMPLE_GAIN_INFO_DATA

typedef enum _roboeffect_user_effect_type_enum
{
	/*Add user define effect ID here*/
	ROBOEFFECT_SIMPLE_GAIN = ROBOEFFECT_USER_DEFINED_EFFECT_BEGIN,
	ROBOEFFECT_TOTAL_MAX,
} roboeffect_user_effect_type_enum;

/*parameters version helper data:*/
#if 0
0x10, 0x00, //3rd party data total length
0x01, //number of 3rd party items

/*simple_gain*/
0x0B, // simple_gain name length
0x01, 0x00, 0x00, // effect version
0x73, 0x69, 0x6D, 0x70, 0x6C, 0x65, 0x5F, 0x67, 0x61, 0x69, 0x6E, 

/*Total length: 18*/

#endif

